// ============================================================================
// RT-Technologie - PM2 Ecosystem Configuration
// ============================================================================
// Description: PM2 configuration for all backend services
// Author: RT-Technologie DevOps Team
// Version: 1.0.0
// Date: 2025-11-18
// ============================================================================

module.exports = {
  apps: [
    {
      name: 'admin-gateway',
      script: './services/admin-gateway/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3008,
      },
      error_file: '/var/log/rt-technologie/admin-gateway-error.log',
      out_file: '/var/log/rt-technologie/admin-gateway-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '500M',
      min_uptime: '10s',
      max_restarts: 5,
      autorestart: true,
      watch: false,
    },
    {
      name: 'authz',
      script: './services/authz/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3007,
      },
      error_file: '/var/log/rt-technologie/authz-error.log',
      out_file: '/var/log/rt-technologie/authz-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '300M',
      autorestart: true,
    },
    {
      name: 'core-orders',
      script: './services/core-orders/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3001,
      },
      error_file: '/var/log/rt-technologie/core-orders-error.log',
      out_file: '/var/log/rt-technologie/core-orders-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '800M',
      autorestart: true,
    },
    {
      name: 'notifications',
      script: './services/notifications/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3002,
      },
      error_file: '/var/log/rt-technologie/notifications-error.log',
      out_file: '/var/log/rt-technologie/notifications-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '300M',
      autorestart: true,
    },
    {
      name: 'planning',
      script: './services/planning/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3004,
      },
      error_file: '/var/log/rt-technologie/planning-error.log',
      out_file: '/var/log/rt-technologie/planning-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '400M',
      autorestart: true,
    },
    {
      name: 'tms-sync',
      script: './services/tms-sync/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3003,
      },
      error_file: '/var/log/rt-technologie/tms-sync-error.log',
      out_file: '/var/log/rt-technologie/tms-sync-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '300M',
      autorestart: true,
    },
    {
      name: 'ecpmr',
      script: './services/ecpmr/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3009,
      },
      error_file: '/var/log/rt-technologie/ecpmr-error.log',
      out_file: '/var/log/rt-technologie/ecpmr-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '400M',
      autorestart: true,
    },
    {
      name: 'vigilance',
      script: './services/vigilance/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3006,
      },
      error_file: '/var/log/rt-technologie/vigilance-error.log',
      out_file: '/var/log/rt-technologie/vigilance-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '300M',
      autorestart: true,
    },
    {
      name: 'palette',
      script: './services/palette/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3011,
      },
      error_file: '/var/log/rt-technologie/palette-error.log',
      out_file: '/var/log/rt-technologie/palette-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '400M',
      autorestart: true,
    },
    {
      name: 'affret-ia',
      script: './services/affret-ia/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3005,
      },
      error_file: '/var/log/rt-technologie/affret-ia-error.log',
      out_file: '/var/log/rt-technologie/affret-ia-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '500M',
      autorestart: true,
    },
    {
      name: 'training',
      script: './services/training/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3012,
      },
      error_file: '/var/log/rt-technologie/training-error.log',
      out_file: '/var/log/rt-technologie/training-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '400M',
      autorestart: true,
    },
    {
      name: 'storage-market',
      script: './services/storage-market/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3013,
      },
      error_file: '/var/log/rt-technologie/storage-market-error.log',
      out_file: '/var/log/rt-technologie/storage-market-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '400M',
      autorestart: true,
    },
    {
      name: 'pricing-grids',
      script: './services/pricing-grids/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3014,
      },
      error_file: '/var/log/rt-technologie/pricing-grids-error.log',
      out_file: '/var/log/rt-technologie/pricing-grids-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '300M',
      autorestart: true,
    },
    {
      name: 'tracking-ia',
      script: './services/tracking-ia/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3015,
      },
      error_file: '/var/log/rt-technologie/tracking-ia-error.log',
      out_file: '/var/log/rt-technologie/tracking-ia-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '400M',
      autorestart: true,
    },
    {
      name: 'bourse',
      script: './services/bourse/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3016,
      },
      error_file: '/var/log/rt-technologie/bourse-error.log',
      out_file: '/var/log/rt-technologie/bourse-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '400M',
      autorestart: true,
    },
    {
      name: 'wms-sync',
      script: './services/wms-sync/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3017,
      },
      error_file: '/var/log/rt-technologie/wms-sync-error.log',
      out_file: '/var/log/rt-technologie/wms-sync-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '300M',
      autorestart: true,
    },
    {
      name: 'erp-sync',
      script: './services/erp-sync/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'fork',
      env: {
        NODE_ENV: 'production',
        PORT: 3018,
      },
      error_file: '/var/log/rt-technologie/erp-sync-error.log',
      out_file: '/var/log/rt-technologie/erp-sync-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '300M',
      autorestart: true,
    },
    {
      name: 'chatbot',
      script: './services/chatbot/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 1,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3019,
      },
      error_file: '/var/log/rt-technologie/chatbot-error.log',
      out_file: '/var/log/rt-technologie/chatbot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '500M',
      autorestart: true,
    },
    {
      name: 'geo-tracking',
      script: './services/geo-tracking/src/server.js',
      cwd: '/opt/rt-technologie',
      instances: 2,
      exec_mode: 'cluster',
      env: {
        NODE_ENV: 'production',
        PORT: 3020,
      },
      error_file: '/var/log/rt-technologie/geo-tracking-error.log',
      out_file: '/var/log/rt-technologie/geo-tracking-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      max_memory_restart: '400M',
      autorestart: true,
    },
  ],

  // Deployment configuration
  deploy: {
    production: {
      user: 'ubuntu',
      host: ['ec2-instance-1.eu-west-3.compute.amazonaws.com', 'ec2-instance-2.eu-west-3.compute.amazonaws.com'],
      ref: 'origin/main',
      repo: 'git@github.com:rt-technologie/rt-technologie.git',
      path: '/opt/rt-technologie',
      'post-deploy': 'pnpm install --frozen-lockfile && pnpm build && pm2 reload pm2-ecosystem.config.js --env production',
      'pre-setup': 'mkdir -p /var/log/rt-technologie',
    },
  },
};
