# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'MobileDriver' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MobileDriver

  # Networking
  pod 'Alamofire', '~> 5.8'

  # TomTom Maps
  pod 'TomTomSDKMapDisplay', '~> 1.0'
  pod 'TomTomSDKRouting', '~> 1.0'

  # QR Code
  pod 'QRCodeReader.swift', '~> 10.1.0'

  # Image Picker
  pod 'YPImagePicker', '~> 5.2'

  # Signature Pad
  pod 'SignaturePad', '~> 1.0'

  target 'MobileDriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MobileDriverUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
